version: '3.4'

services:
  codemaze.web:
    image: ${DOCKER_REGISTRY-}web
    container_name: codemaze_web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - codemaze.db

  codemaze.db:
    image: postgres:13.2
    container_name: codemaze_db
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432